### ISSUE TITLE
Failed to load movies

### ISSUE THREAD

**Issue by shiftylilbastrd** [se1exin/Cleanarr#37]
![image](https://user-images.githubusercontent.com/39231871/131268605-204647ba-f1ad-4913-af83-7b3cd605e3f4.png)
If I choose samples I get results but if I choose duplicates I get the above
![image](https://user-images.githubusercontent.com/39231871/131268659-d5875742-0a3a-4700-a616-2614c80e12a2.png)

**Comment by Flotilla42** [comment]
Been having the same problem for quite a while - I'm guessing that under the hood "Please check your settings" is an error message in a condition somewhere, that happens when all other errors have been "fallen through", and so one could end up with "Please check your settings" even if there are no duplicates or samples to be found. 
That's just my guess though.

**Comment by se1exin** [comment]
Hi @shiftylilbastrd can you please share the Cleanarr log output from when you attempt to load Movies? Unfortunately without the logs it's very hard to know where the issue may be
