### ISSUE TITLE
Failed to load content! Please check your Plex settings and try again.

### ISSUE THREAD

**Issue by mosteanuv** [se1exin/Cleanarr#70]
Hello,

Does anybody know why I get this error:
Failed to load content!
Please check your Plex settings and try again.

?

**Comment by mosteanuv** [comment]
Still can't figure it out!

2022-10-22 07:10:58,786 ERROR    main.py:internal_error HTTPConnectionPool(host='192.168.0.100', port=32400): Read timed out. (read timeout=30)
Sat Oct 22 07:10:58 2022 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /content/dupes (ip 192.168.0.164) !!!
Sat Oct 22 07:10:58 2022 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /content/dupes (192.168.0.164)
OSError: write error
[pid: 36|app: 0|req: 3/52] 192.168.0.164 () {42 vars in 2276 bytes} [Sat Oct 22 07:08:36 2022] GET /content/dupes => generated 0 bytes in 142128 msecs (HTTP/1.1 500) 3 headers in 0 bytes (0 switches on core 0)

**Comment by deepzone1** [comment]
I'm getting :
2022/12/24 05:08:35 [error] 13#13: *31 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.1.121, server: , request: "GET /content/dupes HTTP/1.1", upstream: "uwsgi://unix:///tmp/uwsgi.sock", host: "192.168.1.31", referrer: "http://192.168.1.31/"

Trying to clean 800 items from a movie library with 46 000 items

**Comment by lance-tek** [comment]
I'm getting something similar but on the initial load (before I can even select anything to clean up).  My timeout appears to be around 100 seconds.  I just see the error:

![Screenshot 2023-01-10 at 12 02 21 PM](https://user-images.githubusercontent.com/80020993/211615505-5de933e1-75b2-46ac-8a83-336e5bd8c43c.png)

In my log it simply states:

uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /content/dupes (192.168.30.111)
OSError: write error
[pid: 17|app: 0|req: 4/17] 192.168.30.111 () {40 vars in 605 bytes} [Tue Jan 10 11:52:28 2023] GET /content/dupes => generated 0 bytes in 111529 msecs (HTTP/1.1 200) 3 headers in 0 bytes (0 switches on core 0)

my directory is tens of TBs with a lot of files (and probably a ton of dups)...

**Comment by roggstudelpest** [comment]
I am getting the same issue on larger libraries but working fine on smaller ones. I am now configuring for a single library at a time but the TV Shows library just fails.

**Comment by mxziino** [comment]
I am getting the same issue, i got a large library

**Comment by deepzone1** [comment]
> i have update the script and add a new option : https://github.com/polzy/Cleanarr work for me with frontend and backend and PLEX_TIMEOUT=12000
> 
> If your backend is on a remote server, use this cmd with--host=IP.remote.server :
> 
> PLEX_BASE_URL="http://plex_address:32400" PLEX_TOKEN="somerandomstring" LIBRARY_NAMES="Movies" PLEX_TIMEOUT=12000 FLASK_APP=main python -m flask run --host=IP.remote.server
> 
> and for frontend :
> 
> REACT_APP_BACKEND_URL="http://IP.remote.server:5000/" yarn start

So this is a fork ?  Can you add the docker to the unraid docker repository ? ( kinda a newbie when it comes to dockers )

**Comment by roggstudelpest** [comment]
> 

Yeah I am with you here. How can I get this into my docker image on a Synology NAS?

**Comment by se1exin** [comment]
@polzy 's update has been merged, to those experiencing this issue please try the new `PLEX_TIMEOUT` environment variable and report back with your experiences

**Comment by lance-tek** [comment]
I'm still having the same issue...

For context on my environment:
-Unraid is datastorage (192.168.30.11)
-Plex is on Remote host (192.168.30.219)
--Plex looks to Unraid for files 
---I run the docker from Unraid on with it's own bridged IP (192.168.30.18)
          So, the docker (on Unraid) goes to Plex which goes back to Unraid 
----I look at everything from a client machine (not either of the servers)

I've pulled the latest docker from Unraid and I've set the PLEX_TIMEOUT to various lengths starting at 12000 then doubling it after each failure until I gave up at 96000.


I've tried Chome and Firefox (adjusted browser timeout in this one) but the result is the same on both.  I'm not too smart with Docker or Unraid.  I know enough to make things go and I'm dangerous enough to completely hose my environment.  But, This is all a bit out of my norm so I just try to make sense of it all.

*after the browser shows it timed out and tosses the "Failed to load content! ..." message the logs show that Cleanaar is still flipping through files for a while... until eventually I get :

Thu Jan 19 13:00:05 2023 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /content/dupes (ip 192.168.3.219) !!!
Thu Jan 19 13:00:05 2023 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /content/dupes (192.168.3.219)
OSError: write error
[pid: 15|app: 0|req: 3/14] 192.168.3.219 () {40 vars in 631 bytes} [Thu Jan 19 12:54:07 2023] GET /content/dupes => generated 0 bytes in 358468 msecs (HTTP/1.1 200) 3 headers in 0 bytes (0 switches on core 0)


when the browser shows the timeout message I am seeing this in the Cleanaar logs:

plexwrapper  2023-01-19 12:45:02,647 DEBUG    plexwrapper.py:get_dupe_content Found media: plex://movie/5d776c84fb0d55001f589daa
database     2023-01-19 12:45:02,647 DEBUG    database.py:get_ignored_item content_key /library/metadata/44410

2023/01/19 12:45:03 [error] 11#11: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.30.111, server: , request: "GET /content/dupes HTTP/1.1", upstream: "uwsgi://unix:///tmp/uwsgi.sock", host: "192.168.30.18", referrer: "http://192.168.30.18/"
192.168.30.111 - - [19/Jan/2023:12:45:03 -0500] "GET /content/dupes HTTP/1.1" 504 167 "http://192.168.30.18/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0" "-"

plexwrapper  2023-01-19 12:45:03,041 DEBUG    plexwrapper.py:get_dupe_content Found media: plex://movie/5d77696596b655001fdcda1f
database     2023-01-19 12:45:03,041 DEBUG    database.py:get_ignored_item content_key /library/metadata/40624

**Comment by deepzone1** [comment]
![image](https://user-images.githubusercontent.com/28513111/213527831-e666a806-80ab-4f60-a7f8-acaf1d6a28c9.png)
Getting timeouts still.  Did I set the parameter right ?
Is it possible just to have it in the docker creater/edit page without going into advanced view ?
Btw.. any idea why I have to go into console and create the config directory every time I update or change anything with the docker ?  If not it says : [Errno 2] No such file or directory: '/config/db.json'
Might be because it's never had a successful refresh since it always times out ?

**Comment by roggstudelpest** [comment]
I get the below with a timeout set to 96000. GUI error is "Failed to load content! Please check your Plex settings and try again." and logged error is:

2023/01/20 04:00:59 [error] 11#11: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.17.0.1, server: , request: "GET /content/dupes HTTP/1.1", upstream: "uwsgi://unix:///tmp/uwsgi.sock", host: "192.168.1.185:8008", referrer: "http://192.168.1.185:8008/"

**Comment by lance-tek** [comment]
I ran a few checks today to see if I can figure out the issue.  I looked at Folder Count, File Count, and Directory Size.

In a directory (KidsTV) that was 6.75 TB in size and has 302 Folders (base level) with 6664 files Cleanaar worked
In a directory (KidsVids) which is 1.5 TB in size and has 812 Folders (base level) with 858 files Cleanaar worked
In a directory (TestVids) which was 2.2 TB in size and has 1293 Folder (base level) with 1492 files Cleanaar worked
Then I copied more vids to the (TestVids) directory increasing its contents to 1915 Folders with 5125 files (rescanned the library, optimized the database, refreshed metadata, emptied trash, then rescanned the library and optimized the DB again) I checked Cleanaar and this one failed after adding additional content.  

I've also noticed that if the directory is smaller files (TV) it scans a lot faster (watching logs) and if it is larger (Movie) files it seems to take a LOT longer to flip through.  I thought this was odd since it is presumably using the Plex db/index anyway...

I don't know if this is useful or not but I thought I would share that I found that adding content did cause the failure.  Though it does not appear to be directory size but perhaps file size or number of base level folders.
